# Generated by Django 5.2.9 on 2025-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_del_prov', models.CharField(max_length=255, verbose_name='Identificador del Prov:')),
                ('tit_de_la_cuenta', models.CharField(max_length=255, verbose_name='Titular de la Cuenta:')),
                ('abrev_del_tit', models.CharField(max_length=255, verbose_name='Abreviatura:')),
                ('codigo', models.CharField(max_length=255, verbose_name='Código:')),
                ('cuenta_banc', models.FloatField(verbose_name='Cuenta Bancaria:')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección:')),
            ],
        ),
    ]
