# Generated by Django 5.2.9 on 2025-12-15 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cuenta_banc',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='La cuenta bancaria debe contener exactamente 16 dígitos numéricos.', regex='^\\d{16}$')], verbose_name='Cuenta Bancaria:'),
        ),
    ]
