# Generated by Django 5.2.9 on 2025-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_proveedores_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_H90', models.IntegerField(blank=True, null=True, verbose_name='H90:')),
                ('fecha_del_modelo', models.DateField(verbose_name='Fecha del Modelo')),
                ('forma_de_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], max_length=255, verbose_name='Forma de Pago:')),
                ('cuenta_de_empresa', models.CharField(choices=[('CUP', 'CUP'), ('ANIR', 'ANIR'), ('PRESUPUESTO', 'PRESUPUESTO')], max_length=255, verbose_name='Cuenta de Empresa:')),
            ],
        ),
    ]
