# Generated by Django 5.2.9 on 2025-12-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_solicitudesdepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdepago',
            name='codigo_del_proveedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='direccion_proveedor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='identificador_del_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_de_pago', to='apps.proveedores'),
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='nombre_del_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
