# Generated by Django 5.2.9 on 2025-12-22 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_solicitudesdepago_codigo_del_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('Factura', 'Factura'), ('Prefactura', 'Prefactura'), ('Cotización', 'Cotización'), ('Ninguno', 'Ninguno')], max_length=20, verbose_name='Concepto')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='apps.solicitudesdepago')),
            ],
            options={
                'verbose_name': 'Concepto de pago',
                'verbose_name_plural': 'Conceptos de pago',
                'ordering': ('concepto', 'numero'),
            },
        ),
    ]
