# Generated by Django 4.2.7 on 2026-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_conceptodepago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptodepago',
            options={},
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Importe Total'),
        ),
    ]
