# Generated by Django 4.2.7 on 2026-01-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_conceptodepago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptodepago',
            options={'ordering': ('concepto', 'numero'), 'verbose_name': 'Concepto de pago', 'verbose_name_plural': 'Conceptos de pago'},
        ),
    ]
