# Generated by Django 4.2.7 on 2026-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_conceptodepago_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdepago',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Opcional: escriba cualquier detalle adicional sobre la solicitud.', null=True, verbose_name='Descripción'),
        ),
    ]
