# Generated by Django 4.2.7 on 2026-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_solicitudesdepago_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdepago',
            name='salario',
            field=models.BooleanField(default=False, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='conceptodepago',
            name='concepto',
            field=models.CharField(max_length=50, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='conceptodepago',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
