# Generated by Django 4.2.7 on 2026-01-26 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_solicitudesdepago_salario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('Factura', 'Factura'), ('Prefactura', 'Prefactura'), ('Cotización', 'Cotización'), ('Ninguno', 'Ninguno')], max_length=20, verbose_name='Concepto')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
            ],
            options={
                'verbose_name': 'Concepto normal',
                'verbose_name_plural': 'Conceptos normales',
                'ordering': ('concepto', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='ConceptoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('Salario', 'Salario'), ('Vacaciones', 'Vacaciones'), ('Subsidio', 'Subsidio'), ('Prima', 'Prima'), ('Pago de Utilidades', 'Pago de Utilidades'), ('Reembolso', 'Reembolso')], max_length=30, verbose_name='Concepto')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
            ],
            options={
                'verbose_name': 'Concepto salario',
                'verbose_name_plural': 'Conceptos salario',
                'ordering': ('concepto',),
            },
        ),
        migrations.RemoveField(
            model_name='solicitudesdepago',
            name='salario',
        ),
        migrations.DeleteModel(
            name='ConceptoDePago',
        ),
        migrations.AddField(
            model_name='conceptosalario',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_salarios', to='apps.solicitudesdepago'),
        ),
        migrations.AddField(
            model_name='conceptonormal',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_normales', to='apps.solicitudesdepago'),
        ),
    ]
