# Generated by Django 4.2.7 on 2026-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_conceptonormal_conceptosalario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Total'),
        ),
    ]
