# Generated by Django 4.2.7 on 2026-01-27 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_solicitudesdepago_importe_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonormal',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='conceptonormal',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='conceptosalario',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
    ]
