# Generated by Django 4.2.7 on 2026-01-27 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_conceptonormal_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonormal',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptonormal',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='conceptosalario',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Importe Total'),
        ),
    ]
