# Generated by Django 4.2.7 on 2026-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_conceptonormal_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonormal',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
