# Generated by Django 4.2.7 on 2026-01-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_conceptonormal_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdepago',
            name='importe_inversiones',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Importe de Inversiones'),
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='inversiones',
            field=models.BooleanField(default=False, help_text='Marque si esta solicitud corresponde a inversiones.', verbose_name='Inversiones'),
        ),
    ]
