# Generated by Django 4.2.7 on 2026-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_solicitudesdepago_importe_inversiones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonormal',
            name='numero',
            field=models.CharField(blank=True, help_text='Puede contener números, letras, espacios o caracteres especiales.', max_length=50, null=True, verbose_name='Número'),
        ),
    ]
