# Generated by Django 4.2.7 on 2026-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_conceptonormal_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='numero_de_H90',
            field=models.IntegerField(blank=True, help_text='Número consecutivo por forma de pago y año. Editable, pero no puede repetirse.', null=True, verbose_name='H90:'),
        ),
    ]
