# Generated by Django 4.2.7 on 2026-01-30 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_solicitudesdepago_numero_de_h90'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='fecha_del_modelo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Modelo'),
        ),
    ]
