# Generated by Django 4.2.7 on 2026-01-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_solicitudesdepago_fecha_del_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='fecha_del_modelo',
            field=models.DateField(verbose_name='Fecha del Modelo'),
        ),
    ]
