# Generated by Django 4.2.7 on 2026-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_solicitudesdepago_fecha_del_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdepago',
            name='cancelado',
            field=models.BooleanField(default=False, help_text='Indica si esta solicitud de pago ha sido cancelada.', verbose_name='Cancelado'),
        ),
    ]
