# Generated by Django 4.2.7 on 2026-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_solicitudesdepago_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='cancelado',
            field=models.BooleanField(default=False, help_text='Marque este campo para cancelar la solicitud de pago. Una vez cancelada, no podrá ser modificada.', verbose_name='Cancelado'),
        ),
    ]
