# Generated by Django 4.2.7 on 2026-06-12 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_solicitudesdepago_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionesEmitidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('numero_operacion', models.CharField(max_length=50, unique=True, verbose_name='Número de Operación')),
                ('estado', models.CharField(choices=[('Emitido', 'Emitido'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Emitido', max_length=20, verbose_name='Estado')),
                ('importe_emitido', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe Emitido')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_emitidas', to='apps.solicitudesdepago', verbose_name='Solicitud de Pago')),
            ],
            options={
                'verbose_name': 'Operación Emitida',
                'verbose_name_plural': 'Operaciones Emitidas',
                'ordering': ('-fecha_emision',),
            },
        ),
    ]
