# Generated by Django 4.2.7 on 2026-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_operacionesemitidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesdepago',
            name='cancelado',
        ),
        migrations.AddField(
            model_name='solicitudesdepago',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Emitido', 'Emitido')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
