# Generated by Django 4.2.7 on 2026-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_remove_solicitudesdepago_cancelado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudesdepago',
            options={'verbose_name': 'Solicitud de Pago', 'verbose_name_plural': 'Solicitudes de Pago'},
        ),
        migrations.AlterField(
            model_name='operacionesemitidas',
            name='estado',
            field=models.CharField(choices=[('Tránsito', 'Tránsito'), ('Debitado', 'Debitado'), ('Cancelado', 'Cancelado')], default='Tránsito', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Emitido', 'Emitido'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
