# Generated by Django 4.2.7 on 2026-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_solicitudesdepago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesemitidas',
            name='numero_operacion',
            field=models.CharField(max_length=50, verbose_name='Número de Operación'),
        ),
    ]
