# Generated by Django 4.2.7 on 2026-06-25 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_operacionesemitidas_numero_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesemitidas',
            name='fecha_inicial',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha Inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacionesemitidas',
            name='numero_serie',
            field=models.CharField(default='0000000', max_length=7, validators=[django.core.validators.RegexValidator(message='El Número de Serie debe contener exactamente 7 dígitos numéricos.', regex='^\\d{7}$')], verbose_name='Número de Serie'),
            preserve_default=False,
        ),
    ]
