# Generated by Django 4.2.7 on 2026-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_operacionesemitidas_fecha_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesemitidas',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Final'),
        ),
    ]
