# Generated by Django 4.2.7 on 2026-06-29 14:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_operacionesemitidas_fecha_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_de_empresa', models.CharField(choices=[('CUP', 'CUP'), ('ANIR', 'ANIR'), ('PRESUPUESTO', 'PRESUPUESTO')], max_length=255, verbose_name='Cuenta de Empresa:')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo_ingreso', models.CharField(choices=[('Venta', 'Venta'), ('Reintegro', 'Reintegro'), ('Crédito', 'Crédito'), ('Transferencia', 'Transferencia'), ('Inversiones', 'Inversiones')], max_length=50, verbose_name='Tipo de Ingreso')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('concepto', models.TextField(blank=True, null=True, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ('-fecha',),
            },
        ),
    ]
