# Generated by Django 4.2.7 on 2026-06-29 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='debitar',
            field=models.BooleanField(default=False, help_text='Marque para registrar la fecha de débito automáticamente.', verbose_name='Debitar'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_debito',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Debitó'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha / Fecha Depósito'),
        ),
    ]
