# Generated by Django 4.2.7 on 2026-07-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_ingreso_debitar_ingreso_fecha_debito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': (), 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
