# Generated by Django 4.2.7 on 2026-07-08 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_ingreso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
    ]
