# Generated by Django 4.2.7 on 2026-07-08 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_alter_ingreso_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonormal',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='conceptosalario',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='operacionesemitidas',
            name='importe_emitido',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe Emitido'),
        ),
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='importe_inversiones',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Importe de Inversiones'),
        ),
        migrations.AlterField(
            model_name='solicitudesdepago',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Importe Total'),
        ),
    ]
