# Generated by Django 4.2.7 on 2026-07-08 19:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_alter_conceptonormal_importe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_de_empresa', models.CharField(choices=[('CUP', 'CUP'), ('ANIR', 'ANIR'), ('PRESUPUESTO', 'PRESUPUESTO')], max_length=255, verbose_name='Cuenta de Empresa:')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('clave', models.CharField(choices=[('Chequera', 'Chequera'), ('Comisión de Nómina', 'Comisión de Nómina'), ('Aporte', 'Aporte'), ('Centro de Pago', 'Centro de Pago'), ('Comisión', 'Comisión'), ('Otro', 'Otro')], max_length=50, verbose_name='Clave')),
                ('descripcion', models.TextField(blank=True, help_text="Obligatorio solo si selecciona 'Otro' en Clave.", null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Servicio Bancario',
                'verbose_name_plural': 'Servicios Bancarios',
                'ordering': (),
            },
        ),
    ]
