# Generated by Django 4.2.7 on 2026-07-09 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_serviciobancario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInversiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_de_empresa', models.CharField(choices=[('CUP', 'CUP'), ('ANIR', 'ANIR'), ('PRESUPUESTO', 'PRESUPUESTO')], max_length=255, verbose_name='Cuenta de Empresa:')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Puede ingresar valores positivos o negativos.', max_digits=20, verbose_name='Importe')),
                ('clave', models.CharField(choices=[('Contravalor', 'Contravalor'), ('Otro', 'Otro')], max_length=50, verbose_name='Clave')),
                ('descripcion', models.TextField(blank=True, help_text="Obligatorio solo si selecciona 'Otro' en Clave.", null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ajuste de Inversión',
                'verbose_name_plural': 'Ajustes de Inversiones',
                'ordering': (),
            },
        ),
    ]
